
name: 🚀 Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_call:
    inputs:
      package_name:
        description: "Package Name"
        required: true
        type: string
      version:
        required: true
        description: "Package Version"
        type: string

jobs:
  windows:
    uses: ./.github/workflows/deploy_windows.yml
    with:
      package_name: ${{ inputs.package_name }}
      version: ${{ inputs.version }}
    secrets: inherit

  linux:
    uses: ./.github/workflows/deploy_linux.yml
    with:
      package_name: ${{ inputs.package_name }}
      version: ${{ inputs.version }}
    secrets: inherit

  mac-armv8:
    uses: ./.github/workflows/deploy_mac.yml
    with:
      package_name: ${{ inputs.package_name }}
      version: ${{ inputs.version }}
    secrets: inherit