name: Windows CI

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        required: true
        type: string
      version:
        description: 'Package version'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log Target Repo Info
        run: |
          echo "Processing CI for repository type: ${{ inputs.repo }}"

      - name: Conditional Build Step
        run: |
            echo "${{ inputs.repo}}"
            echo "${{ inputs.version }}"

      - name: Run Tests
        if: ${{ inputs.version }}
        run: |
          echo "Executing test suite..."